version: '3'
name: mnemonics
services:
  azure-sql-server:
    container_name: mnemonics-sql-db
    image: "mcr.microsoft.com/azure-sql-edge"
    restart: always
    ports:
      - "1455:1433"
    environment:
      - SA_PASSWORD=$SA_PASSWORD
      - ACCEPT_EULA=Y
    volumes:
      - ../../../AppLogsAndDB/TelegramEngBot_DB:/var/opt/mssql/data
  